<?php /* Template Name: Community Support Tempalte */ ?>
<?php

get_header();

$is_page_builder_used = et_pb_is_pagebuilder_used( get_the_ID() );
?>

<div id="main-content">
        <!-- top header banner -->
        <div class="global-content-banner-row m_0 has-image-banner top-header-banner">
                <div class="global-content-banner-column community-support-banner-column image_column">
                    <div class="global-content-banner-module top-header-banner__inner position_relative">
                        <h1 class="p_0 global-content-banner-heading color_white font_helvetica font_bold text_uppercase">COMMUNITY SUPPORT</h1>
                        <div class="global-content-banner-para-wrapper">
                        <p class="p_0 global-content-banner-para color_white font_helvetica font_bold global-content-first-para">Durango Motor Company is pleased to support our community by giving back to and being actively involved with the following organizations, groups and events: Bayfield Schools, Boys & Girls Club of La Plata County, Fort Lewis College Athletics, La Plata Family Centers Coalition, Music in the Mountains ...just to name a few</p>
                        </div>
                    </div>
                </div>
        	</div>
            <!-- top header banner ended -->
            <!-- community support content section started -->
            <div class="global-content-row">
                <div class="global-content-column-first">
                    <h3 class="font_helvetica global-content-primary-heading  p_0 font_bold" style="margin-bottom:20px;">
                    Request A Donation/Sponsorship
                    </h3>
                    <p class="global-content-primary-para p_0">
                    Durango Value Autos gives willingly to and is actively involved in the support of our communities, because they provide us our success. We are dedicated to offering donations and sponsorships to local not-for-profit programs, groups, and causes that positively impact our community.  <br> Our Contributions Committee meets the second week of each month, and all requests must be received at lest 30 days prior to the date the donation is needed.
                    </p>
                    <h3 class="font_helvetica global-content-primary-heading  p_0 font_bold" style="margin-bottom:5px; padding-top:25px ;">
                    To Be Considered By The Contributions Committee, All Requests Must Include:
                    </h3>
                    <ol class="global-content-left-list-wrapper" style="list-style:auto;">
                        <li>Contact Info including <b>ALL</b> of the following; Organization/Event Name, Date of Event, Contact Name, Phone Number, Email Address,  Mailing Address</li>
                        <li>Be submitted in writing at least <b>30 days prior</b> to the date the donation is neede</li>
                        <li>Provide proper tax-exempt status as a 501(c)(3) organization</li>
                        <li>Indicate how the funds generated by the donation item(s) and/or how the cash donation will be used by the organization</li>
                        <li>Indicate how the sponsorship funding will be used to support the event and the organization.</li>
                        <li>Provide a brief summary of the organization and how it benefits the individuals and our community at large</li>
                        <li>Be specific with regard to item(s) requested (with the understanding that the Committee will use this only as a guideline, and may choose a different item, if any)</li>
                    </ol>
                    <h3 class="font_helvetica global-content-primary-heading  p_0 font_bold text_uppercase community-support-text">
                    community support
                    </h3>
                    <p class="global-content-primary-para">
                    Durango Motor Company is pleased to support our community by giving back to and being actively involved with the following organizations, groups, and events. For more information on our community involvement or to submit a request for a donation or sponsorship, <a href="https://www.durangomotorcompany.com/request-a-donation-durango-co" target="_blank"> please click here</a>.
                    </p>
                    <div class="community-highlights-row d_grid community-support-row">
                        <div class="community-highlights-column">
                            <p class="font-segoe text_center">
                            Adaptive Sports Association
                            </p>
                            <div class="community-support-img-wrapper">
                                <img src="<?php echo site_url(); ?>/wp-content/themes/divi-child/assets/images/Adaptive-Sports-Association.webp" alt="adaptive sports accociation">
                            </div>
                        </div>
                        <div class="community-highlights-column">
                            <p class="font-segoe text_center">
                            Music In The Mountains
                            </p>
                            <div class="community-support-img-wrapper">
                                <img src="<?php echo site_url(); ?>/wp-content/themes/divi-child/assets/images/Music-in-the-Mountains.webp" alt="music in mountains">
                            </div>
                        </div>
                        <div class="community-highlights-column">
                            <p class="font-segoe text_center">
                            Boys and Girls Club of La Plata County
                            </p>
                            <div class="community-support-img-wrapper">
                                <img src="<?php echo site_url(); ?>/wp-content/themes/divi-child/assets/images/Boys-and-Girls-Club-of-La-Plata-County.webp" alt="boys and girls club of la">
                            </div>
                        </div>
                        <div class="community-highlights-column">
                            <p class="font-segoe text_center">
                            Fort Lewis College Athletic Program
                            </p>
                            <div class="community-support-img-wrapper">
                                <img src="<?php echo site_url(); ?>/wp-content/themes/divi-child/assets/images/Fort-Lewis-College-Athletic-Program2.webp" alt="fort lewis college athletic program">
                            </div>
                        </div>
                        <div class="community-highlights-column">
                            <p class="font-segoe text_center">
                            Fort Lewis College Athletic Program
                            </p>
                            <div class="community-support-img-wrapper">
                                <img src="<?php echo site_url(); ?>/wp-content/themes/divi-child/assets/images/Fort-Lewis-College-Athletic-Program.webp" alt="fort lewis college">
                            </div>
                        </div>
                        <div class="community-highlights-column">
                            <p class="font-segoe text_center">
                            Riverview Elementary Fun Run
                            </p>
                            <div class="community-support-img-wrapper">
                                <img src="<?php echo site_url(); ?>/wp-content/themes/divi-child/assets/images/Riverview-Elementary-Fun-Run.webp" alt="riverview elementary fun run">
                            </div>
                        </div>
                        
                    </div>

                    <div class="community-main-highlight" style="margin-top:30px;">
                    <img src="<?php echo site_url(); ?>/wp-content/themes/divi-child/assets/images/community-new.webp" alt="community news" class="w_100">
                    </div>

                </div>
                <div class="global-content-columns-second">
                    <div class="global-side-block">
                    <h3 class="font_segoe global-content-primary-heading  p_0 font_bold text_capitalize global-content-right-primary-heading d_block">Submit Requests To:</h3>
                    <ul class="global-content-right-list-wrapper pl_0">
                    <li class="global-content-right-list"><span style="font-size:17px;font-weight: 600;">Email:</span><br> <a href="javascript:void(0)" data-copy="marketing@durangomotorcompany.com" class="text-third copy-value global-content-right-list-wrapper d_inline-block global-content-right-lists-item font_helvetica text_capitalize company-marketing-email">marketing@durangomotorcompany.com</a></li>
                    <li class="global-content-right-list"><span style="font-size:17px;font-weight: 600;">Mail:</span><br> <p class="global-content-right-list-wrapper d_inline-block global-content-right-lists-item font_helvetica text_capitalize">Durango Motor Company</p></li>
                    <li class="global-content-right-list"><span class="d_inline-block" style="font-size:17px;font-weight: 600; margin-bottom:5px;">Attn:</span><br> 
                        <p class="global-content-primary-para">Taylor Hinnant <br> 1200 Carbon Junction, Durango, CO 81301</p>
                        <i style="line-height:1.6;">Please note that a donation or sponsorship granted by Durango Motor Company/Durango Value Autos should not be considered as a guaranteed commitment in the future. Durango Motor Company receives hundreds of requests each year making it impossible to accommodate every organization on an annual basis. A member of our Committee will follow up if we are able to accommodate your request.</i>
                    </li>
                    </ul>
                    </div>
                </div>
            </div>
            <!-- community support content section ended -->
</div>

    <?php

get_footer();

?>

